--- 
- name: Install nginx 
  hosts: all 
  vars:
    location_here: 'Subotica'
    packages:
      - nginx
      - vim
      - htop
    services:
      - nginx
  become: true 
 
  tasks: 
    - name: Install packages 
      package:
        name: "{{ packages }}"
    - name: Start services 
      service: 
        name: "{{ services }}" 
        state: started 
    - name: Modify Web 
      copy: 
        content: '<h2>Hello from {{ location_here }}</h2>' 
        dest: /var/www/html/index.html 
    - name: Create group wheel
      group:
        name: wheel
    - name: Create user Darko 
      user: 
        name: darko 
        comment: "Darko Meszaros" 
        uid: 1040 
        group: wheel 
    - name: Create user Bob 
      user: 
        name: bob 
        comment: "Darko loves .asCode" 
        group: wheel 
